services:
  orderer.teknixco.com:
    container_name: orderer.teknixco.com
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/genesis.block
      - ./crypto-config/ordererOrganizations/teknixco.com/orderers/orderer.teknixco.com/msp:/var/hyperledger/orderer/msp
    ports:
      - 7050:7050
    networks:
      - fabric

  peer0.org1.teknixco.com:
    container_name: peer0.org1.teknixco.com
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.teknixco.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.teknixco.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.teknixco.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.teknixco.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.teknixco.com:7051
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/peer/msp
      - CORE_PEER_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/org1.teknixco.com/peers/peer0.org1.teknixco.com/msp:/var/hyperledger/peer/msp
      - ./crypto-config/peerOrganizations/org1.teknixco.com/users:/var/hyperledger/peer/users
    ports:
      - 7051:7051
    networks:
      - fabric

  ca.org1.teknixco.com:
    container_name: ca.org1.teknixco.com
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=7054
    command: fabric-ca-server start -b admin:adminpw
    ports:
      - 7054:7054
    volumes:
      - ./crypto-config/peerOrganizations/org1.teknixco.com/ca:/etc/hyperledger/fabric-ca-server-config
    networks:
      - fabric

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:2.5
    tty: true
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.teknixco.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@org1.teknixco.com/msp
      - CORE_PEER_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config:/etc/hyperledger/crypto-config
      - ./channel-artifacts:/etc/hyperledger/channel-artifacts
      - ./scripts:/etc/hyperledger/scripts
    depends_on:
      - orderer.teknixco.com
      - peer0.org1.teknixco.com
    networks:
      - fabric

networks:
  fabric:
    driver: bridge
